# this line does quite a bit, so let's break it down
#
# find soh
# use "find" to look in the "soh" directory
# this ensures we don't try to format stuff in the submodules
#
# -type f
# only look for files
#
# -name "*.c" -o -name "*.cpp"
# find all .c and .cpp files
#
# ( -name "*.h" -o -name "*.hpp" ) ! -path "soh/src/**.h" ! -path "soh/include/**.h"
# find all .h and .hpp files that aren't in soh/src or soh/include
# this is because zret decomp only runs clang-format on c files
# https://github.com/zeldaret/mm/blob/b7e5468ca16315a7e322055eff3d97fe980bbc25/format.py#L182
#
# ! -path "soh/assets/*"
# asset headers are autogenerated, don't fight them
#
# -print0
# separate paths with NUL bytes, avoiding issues with spaces in paths
#
# | xargs -0 clang-format-14 -i -verbose
# use xargs to take each path we've found
# and pass it as an argument to clang-format
# verbose to print files being formatted and X out of Y status

# ComboShip: format BOTH games' trees. soh/ mirrors upstream Shipwright; mm/ mirrors upstream
# 2ship2harkinian (HarbourMasters/2ship2harkinian/run-clang-format.sh) — same shape: format .c/.cpp
# everywhere, format .h/.hpp except the decomp header dirs (src/ and include/), and skip the
# autogenerated assets/ headers. clang-format picks each file's nearest .clang-format (soh/.clang-format
# vs mm/.clang-format) automatically, so vendored decomp already-formatted upstream stays a no-op here.
find soh mm -type f \( -name "*.c" -o -name "*.cpp" -o \( \( -name "*.h" -o -name "*.hpp" \) ! -path "soh/src/*" ! -path "soh/include/*" ! -path "mm/src/*" ! -path "mm/include/*" \) \) ! -path "soh/assets/*" ! -path "mm/assets/*" -print0 | xargs -0 clang-format-14 -i --verbose
