message(STATUS "Copying otr files...")

# soh.o2r — generated in soh/ working directory (GenerateSohOtr)
if(NOT ONLY2SHIPOTR AND EXISTS ${SOURCE_DIR}/soh/soh.o2r)
    execute_process(COMMAND ${CMAKE_COMMAND} -E copy soh.o2r ${BINARY_DIR}/soh/soh.o2r)
    message(STATUS "Copied soh.o2r")
    if(SYSTEM_NAME MATCHES "Windows")
        execute_process(COMMAND ${CMAKE_COMMAND} -E copy soh.o2r ${TARGET_DIR}/soh.o2r)
    endif()
endif()

# mm.o2r (user-provided ROM archive) and 2ship.o2r (generated in mm/ working directory)
if(NOT ONLYSOHOTR)
    if(NOT ONLY2SHIPOTR AND EXISTS ${SOURCE_DIR}/mm/mm.o2r)
        execute_process(COMMAND ${CMAKE_COMMAND} -E copy mm.o2r ${SOURCE_DIR}/mm.o2r)
        execute_process(COMMAND ${CMAKE_COMMAND} -E copy mm.o2r ${BINARY_DIR}/mm/mm.o2r)
        message(STATUS "Copied mm.o2r")
        if(SYSTEM_NAME MATCHES "Windows")
            execute_process(COMMAND ${CMAKE_COMMAND} -E copy mm.o2r ${TARGET_DIR}/mm.o2r)
        endif()
    endif()
    if(EXISTS ${SOURCE_DIR}/mm/2ship.o2r)
        execute_process(COMMAND ${CMAKE_COMMAND} -E copy 2ship.o2r ${SOURCE_DIR})
        execute_process(COMMAND ${CMAKE_COMMAND} -E copy 2ship.o2r ${BINARY_DIR}/mm/)
        message(STATUS "Copied 2ship.o2r")
        if(SYSTEM_NAME MATCHES "Windows")
            execute_process(COMMAND ${CMAKE_COMMAND} -E copy 2ship.o2r ${TARGET_DIR})
        endif()
    endif()
endif()

# Validation
if(NOT ONLY2SHIPOTR AND NOT EXISTS ${SOURCE_DIR}/soh/soh.o2r)
    message(FATAL_ERROR "Failed to copy. No soh.o2r found.")
endif()
if(NOT ONLYSOHOTR AND NOT ONLY2SHIPOTR AND NOT EXISTS ${SOURCE_DIR}/mm/mm.o2r)
    message(WARNING "No mm.o2r found — user ROM archive may be missing.")
endif()
if(NOT ONLYSOHOTR AND NOT EXISTS ${SOURCE_DIR}/mm/2ship.o2r)
    message(FATAL_ERROR "Failed to copy. No 2ship.o2r found.")
endif()
